### ISSUE TITLE
Get Balance from address

### ISSUE THREAD

**Issue by gallaz-cvl** [ock666/python-blockchain#19]
```
Example:
http://localhost:5000/balance?address=d7cb5e083675122fb589cd3435e00a95497029d7

Return:
{
	"address": "d7cb5e083675122fb589cd3435e00a95497029d7",
	"balance": 630
}
```

```py
@app.route('/balance', methods=['GET'])
def balance():
    address = request.args.get('address')
    
    if address is None:
        return 'Missing address', 400
    else:
        balance = Validation.enumerate_funds(address, blockchain.chain)
    
    if balance > 0:
        response = {
            'address': address,
            'balance': balance,
        }
        return jsonify(response), 200
```

How do you know if the address is a valid address and is inside the blockchain?

**Comment by ock666** [comment]
> How do you know if the address is a valid address and is inside the blockchain?

The enumerate_funds function doesn't check if an address is valid. 

Only if a given address has balance on the blockchain.  If a provided address isnt on the blockchain, enumerate funds will simply return False.

You may wish to add something like this to your function.

```
if not balance:
    response = {
             'address': address,
             'balance': 0,
}
   return jsonify(response)
```
I'm by no means a python expert so theres probably a better way to format the function.

Let me know if this helps/solves your problem.

**Comment by gallaz-cvl** [comment]
Thanks for your interest, I'm not a Python expert either. I liked your work based on the article you mentioned in the description.

I think with your help I have managed to get the function to work without errors.

I have put first an If to know if the length of the address is 40 characters. And then the part of the code you recommended.

```py
@app.route('/balance', methods=['GET'])
def balance():
    address = request.args.get('address')
    
    if address is None:
        return 'Missing address', 400
    
    if len(address) < 40 or len(address) > 40:
        return 'Invalid address', 400
    
    bal = Validation.enumerate_funds(address, blockchain.chain)
    
    if bal >= 0:
        response = {
            'address': address,
            'balance': bal,
        }
        return jsonify(response), 200
    
    # If balance is false, the address no found on blockchain
    if not bal:
        response = {
            'address': address,
            'balance': bal,
        }
        return jsonify(response), 200

```

How can I add a header to the address?
This way you can better identify if an address belongs to the blockchain or not.

Example: PTd7cb5e083675122fb589cd3435e00a95497029d7
The initial characters 'PT' (PythonToken) is a header for the rest address.

**Comment by ock666** [comment]
> How can I add a header to the address?

to be honest i havent really looked into adding headers to blocks or addresses, its a feature i may consider later down the line.

Currently the way an address is generated is a two part hash of the wallets public key. 


SHA256 and then RIPEMD160 I think just from the top of my head. The method for this is in utils.generate_wallet function. 

You could verify an address is valid by taking the public key hex from a transaction and hashing it the same way as that function and checking if that result is the same as the provided address in the transaction. I think that might be a handy additional check function to add to the Validation.py file.
