### ISSUE TITLE
Remove node

### ISSUE THREAD

**Issue by gallaz-cvl** [ock666/python-blockchain#21]
Here I bring you another piece of code that can be useful to remove nodes.
This time the idea is from this other project.
https://github.com/stevenplatt/tcp_air/blob/main/network_chain3.py

Inside the Blockchain class and between the function register_node and valid_chain we add this function.
```py
def remove_node(self, address):
        """
        Remove a node from the list of nodes
        :param address: <str> Address of node. Eg. 'http://192.168.0.5:5000'
        :return: None
        """
        
        parsed_url = urlparse(address)
        self.nodes.remove(parsed_url.netloc)
```

And between the flask function register_nodes and consensus we add this other function.
```py
@app.route('/nodes/remove', methods=['POST'])
def remove_nodes():
    values = request.get_json()
    
    nodes = values.get('nodes')
    if nodes is None:
        return "Error: Please supply a valid list of nodes", 400
    
    for node in nodes:
        blockchain.remove_node(node)
    
    response = {
        'message': 'Node has been remove',
        'total_nodes': list(blockchain.nodes),
    }
    return jsonify(response), 202

```

**Comment by ock666** [comment]
I really like the remove node function, as one doesn't currently exist in the code base.
However I think it may be worth calling that function after a number of failed attempts at sharing a block or a new transaction in the mempool to a registered node. As opposed having it as an API endpoint anybody could send a request to, to remove a node from another node.
